<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * InquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InquiryRepository extends EntityRepository
{
    public function findAllByKeyword($keyword)
    {
        $query = $this->createQueryBuilder('i')
            ->where('i.name LIKE :keyword')
            ->orWhere('i.tel LIKE :keyword')
            ->orWhere('i.email LIKE :keyword')
            ->orderBy('i.id', 'DESC')
            ->setParameters([
                ':keyword' => '%'.$keyword.'%'
            ])
            ->getQuery();
        return new ArrayCollection($query->getResult());
    }

    public function findUnprocessed()
    {
        $query = $this->createQueryBuilder('i')
            ->where('i.processStatus = :processStatus')
            ->orWhere('i.processStatus is null')
            ->orderBy('i.id', 'ASC')
            ->setParameter('processStatus', '0') // 注意：ここも小文字で
        ->getQuery();
        return $query->execute();
    }
}
